### ISSUE TITLE
blank v9 screen

### ISSUE THREAD

**Issue by intaeksong** [vertex-analytics/docs#4]
I'm using Chrome and nothing is showing up on V9. V3 works fine on the same machine and browser. 

Google Chrome is up to date
Version 84.0.4147.125 (Official Build) (64-bit)

Here is a snapshot of my screen:
![v9](https://user-images.githubusercontent.com/31211003/90280080-f1d02280-de2f-11ea-8c13-993503897681.jpg)

**Comment by PlGGS** [comment]
Please use http rather than https

**Comment by intaeksong** [comment]
That works, thanks!
